### ISSUE TITLE
The Pricay Shield isn't enough according to EU. The page doesn't reflect that

### ISSUE THREAD

**Issue by SGL70** [MicrosoftDocs/Compliance#10]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87dd6312-7b6c-5535-5b12-d08ef3e46ddd
* Version Independent ID: 7e449397-c6ba-1562-d920-ac2f9ab6cc24
* Content: [General Data Protection Regulation - Microsoft GDPR](https://docs.microsoft.com/en-us/compliance/regulatory/gdpr#gdpr-faqs)
* Content Source: [compliance/regulatory/gdpr.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/gdpr.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please add your comment and help us in resolving this issue. Thanks.

**Comment by yogkumgit** [comment]
@robmazz

**Comment by robmazz** [comment]
@SGL70 - thanks for your feedback, this has been updated in the GDPR topic.
