### ISSUE TITLE
Link to Azure FDA guides doesn't work

### ISSUE THREAD

**Issue by tomnolan** [MicrosoftDocs/Compliance#102]
Down in the How to Implement section, the last bullet says

> FDA CFR Title 21 Part 11 Guides: Get help establishing an [Azure](https://aka.ms/Azure-FDA-Guidelines) and [Office 365](https://aka.ms/o365-qualification-guideline) qualification strategy that complies with FDA guidelines for electronic records.

The Azure link just goes to a code search page on the Azure site. No documentation actually comes up. the Aka.ms owner for that short link should update that to direct to the documentation as appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a39125-16b6-7657-b5dd-210fc4d70fcf
* Version Independent ID: 298792b1-d33f-f6ba-3a3b-52358d744ace
* Content: [Good Clinical, Laboratory, and Manufacturing Practices (GxP) - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-gxp)
* Content Source: [compliance/regulatory/offering-gxp.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-gxp.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@tomnolan - thanks for the feedback, updating the link to point to the correct location: https://azure.microsoft.com/en-us/resources/microsoft-azure-gxp-guidelines-april/
