### ISSUE TITLE
is bookings app certificated by IRAP？

### ISSUE THREAD

**Issue by tommyoo2** [MicrosoftDocs/Compliance#103]
is bookings app certificated by IRAP？

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e2b0546-e761-9327-2e8c-f12a9e9094e0
* Version Independent ID: aeac0cec-75b5-d99c-63fb-06c3e14266ec
* Content: [Australian Government Information Security Registered Assessor Program (IRAP) - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-irap-australia)
* Content Source: [compliance/regulatory/offering-IRAP-Australia.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-IRAP-Australia.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by tommyoo2** [comment]
@robmazz  may I know the update?

**Comment by robmazz** [comment]
@tommyoo2 - not that I know of, I've not been contacted to add it to this documentation. But please reach out to your local Microsoft account manager for confirmation.
