### ISSUE TITLE
ISO 27001 - Yammer service

### ISSUE THREAD

**Issue by manuel-faria** [MicrosoftDocs/Compliance#104]
I cannot find Yammer within in-scope services for ISO 27001 certification. Does it not comply with this certification?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 014c96d4-b256-7eb5-c227-3fa6090be7e7
* Version Independent ID: cb3d94bb-30a6-ccc0-9648-457e0dae770a
* Content: [ISO/IEC 27001:2013 Information Security Management Standards - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-ISO-27001?view=o365-worldwide)
* Content Source: [compliance/regulatory/offering-ISO-27001.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-ISO-27001.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@manuel-faria - thanks for the feedback. I'll double-check with the PG team about Yammer and update accordingly. If you need immediate confirmation, please open a ticket with Microsoft Support.
