### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by LS16395762** [MicrosoftDocs/Compliance#108]
the link for "[Office 365 Core - SSAE 18 SOC 2 Report](https://servicetrust.microsoft.com/ViewPage/MSComplianceGuideV3?command=Download&downloadType=Document&downloadId=b8f3942c-845e-418f-8f6e-329dbf6efce0&tab=7027ead0-3d6b-11e9-b9e1-290b1eb4cdeb&docTab=7027ead0-3d6b-11e9-b9e1-290b1eb4cdeb_SOC_%2F_SSAE_16_Reports)"

is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8017e3db-1948-bfbe-ebde-b95b436659ba
* Version Independent ID: 7c86a1d0-7753-8d61-6882-8b644e5fbcb0
* Content: [System and Organization Controls (SOC) 2 Type 2 - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-soc-2)
* Content Source: [compliance/regulatory/offering-soc-2.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-soc-2.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@LS16395762 - thanks for the feedback. The updated link is https://servicetrust.microsoft.com/DocumentPage/d4d3bd80-8c53-416a-93f9-a0115d883779. Updating in the article, thanks again.
