### ISSUE TITLE
Link to 'Response to EBA guidance' is broken

### ISSUE THREAD

**Issue by jonasanker** [MicrosoftDocs/Compliance#112]
The link to the [Response to EBA guidance ](https://aka.ms/FinServ-Guide-EuBankAuth) listed in the _How to implement_ section shows that the document is not found when visiting the page.

![image](https://user-images.githubusercontent.com/25930103/192778414-f2e495b2-5e2b-4aa9-9614-74148705ad5c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db0fe979-8a47-820f-7ca8-ad0bb05e16fe
* Version Independent ID: dd7649dd-6ce2-279b-2f86-9c91c62d14c3
* Content: [European Banking Authority (EBA) - Microsoft Compliance](https://learn.microsoft.com/en-us/compliance/regulatory/offering-eba-eu#feedback)
* Content Source: [compliance/regulatory/offering-EBA-EU.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-EBA-EU.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@jonasanker - thanks for the feedback. I believe the most current link is: https://servicetrust.microsoft.com/DocumentPage/2f18eb43-64df-424c-8d59-98c18b7cb9e0. Updating in the article, but if you have further questions, please contact your Microsoft Customer Support representative.
