### ISSUE TITLE
Resource link broken

### ISSUE THREAD

**Issue by SkipSnowArchitect** [MicrosoftDocs/Compliance#113]
[DoD Cloud Computing Security Requirements Guide](https://dl.dod.cyber.mil/wp-content/uploads/cloud/SRG/index.html)

This link is broken on this page
https://learn.microsoft.com/en-us/compliance/regulatory/offering-dod-il5
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f09b4f65-0b35-6330-87ef-6f3676a9385d
* Version Independent ID: 677f48f1-f227-848c-52e8-8198f3d8d800
* Content: [Department of Defense (DoD) Impact Level 5 (IL5) - Microsoft Compliance](https://learn.microsoft.com/en-us/compliance/regulatory/offering-dod-il5)
* Content Source: [compliance/regulatory/offering-dod-il5.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-dod-il5.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@SkipSnowArchitect - thanks for the feedback, removed link from resources list. If you need additional resources from dl.dod.cyber.mil, please visit their site directly.
