### ISSUE TITLE
Dead link under resources section

### ISSUE THREAD

**Issue by quickclix75** [MicrosoftDocs/Compliance#115]
Hi...

The link to the **PCI DSS Quick Reference Guide** results in a 404.. checking the site, it appears the PDF file changes its name when updated. Please change the link on the doc to point to the publication page as opposed to the PDF as I suspect it will change again in the future thanks ! 👍🏻

https://www.pcisecuritystandards.org/document_library/?document=pci_ssc_quick_reference_guide

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3a6e0c-49bc-7290-923d-c4966f9d1de5
* Version Independent ID: b94d3d1e-d84f-f46d-c967-c80416a46f94
* Content: [Payment Card Industry (PCI) Data Security Standard (DSS) - Microsoft Compliance](https://learn.microsoft.com/en-us/compliance/regulatory/offering-pci-dss)
* Content Source: [compliance/regulatory/offering-PCI-DSS.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-PCI-DSS.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@quickclix75 - thanks for the feedback, link updated in the article.
