### ISSUE TITLE
Links outdated

### ISSUE THREAD

**Issue by anjanesh-babu-HomeOffice** [MicrosoftDocs/Compliance#116]
[Enter feedback here]
https://aka.ms/UK-G-Cloud -- is  pointing to  guidance  withdrawn on 9 June 2016
https://www.gov.uk/government/publications/cloud-service-security-principles/cloud-service-security-principles

[Effective Compliance Controls to Address the UK Governments Common 14 Cloud Security Principles Using Microsoft Azure](https://aka.ms/complianceuk)
Is being redirected to Bing Search
https://www.bing.com/?ref=aka&shorturl=complianceuk

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb451de8-5273-f27c-2f5d-254fe4b6a6af
* Version Independent ID: 8910bd02-fd6d-bde9-1e0d-4a540bad2fa6
* Content: [United Kingdom Government-Cloud (G-Cloud) - Microsoft Compliance](https://learn.microsoft.com/en-us/compliance/regulatory/offering-g-cloud-uk)
* Content Source: [compliance/regulatory/offering-G-Cloud-UK.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-G-Cloud-UK.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@anjanesh-babu-HomeOffice - thanks for the feedback, removed the resource links.
