### ISSUE TITLE
Azure Devops missing in PCI certification

### ISSUE THREAD

**Issue by steunet** [MicrosoftDocs/Compliance#117]
Why Azure devops is  missing in PCI certitication?
Is it becouse you have to open FW port to let comunication with agents and local resource for doing deployment?
Ste

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3a6e0c-49bc-7290-923d-c4966f9d1de5
* Version Independent ID: b94d3d1e-d84f-f46d-c967-c80416a46f94
* Content: [Payment Card Industry (PCI) Data Security Standard (DSS) - Microsoft Compliance](https://learn.microsoft.com/en-us/compliance/regulatory/offering-pci-dss)
* Content Source: [compliance/regulatory/offering-PCI-DSS.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-PCI-DSS.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@steunet - thanks for the feedback. Please open support ticket with Microsoft Customer Service for this issue.
