### ISSUE TITLE
unable to download report.

### ISSUE THREAD

**Issue by maramraghavendra** [MicrosoftDocs/Compliance#119]
[Office 365: ISO 27001, 27018, and 27017 Audit Assessment Report](https://servicetrust.microsoft.com/ViewPage/MSComplianceGuide?command=Download&downloadType=Document&downloadId=8873fa17-9962-4be9-b0d0-086262eb84fb) and says no documents found and unable downlaod.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5dd2eafd-d260-c322-3dba-309683564979
* Version Independent ID: 54d74a8f-e1fc-46bb-16f5-829e3f6eeb5a
* Content: [ISO/IEC 27018 Code of Practice for Protecting Personal Data in the Cloud - Microsoft Compliance](https://learn.microsoft.com/en-us/compliance/regulatory/offering-iso-27018)
* Content Source: [compliance/regulatory/offering-ISO-27018.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-ISO-27018.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@maramraghavendra - thanks for the feedback. Updating the article with the correct link: https://servicetrust.microsoft.com/DocumentPage/c8725e07-e724-4336-9f87-1ffcee9fffb1
