### ISSUE TITLE
Add "Windows 365" to SOC 2 Type II certified service

### ISSUE THREAD

**Issue by kmsft** [MicrosoftDocs/Compliance#126]
Please add "Windows 365" as a service in the Commercial cloud section under Office 365.  Windows 365 is now SOC 2 Type II certified in Commercial following the most recent audit that completed this week.  The audit report listing Windows 365 can be found at: https://servicetrust.microsoft.com/DocumentPage/74da20e0-e84e-425f-862c-951734cd2fa0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8017e3db-1948-bfbe-ebde-b95b436659ba
* Version Independent ID: 7c86a1d0-7753-8d61-6882-8b644e5fbcb0
* Content: [System and Organization Controls (SOC) 2 Type 2 - Microsoft Compliance](https://learn.microsoft.com/en-us/compliance/regulatory/offering-soc-2)
* Content Source: [compliance/regulatory/offering-soc-2.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-soc-2.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@kmsft - please use the internal MS content request process, reach out to me via email or teams for details. Thanks!
