### ISSUE TITLE
Links are wrong

### ISSUE THREAD

**Issue by tmoen2015** [MicrosoftDocs/Compliance#14]
Link to CGCC takes you to hethcare site
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 511a3ec9-30d0-2541-b430-131354de6959
* Version Independent ID: 76e2259f-18af-ee2f-5026-bc3340a51bc3
* Content: [US Internal Revenue Service Publication 1075 - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-irs-1075)
* Content Source: [compliance/regulatory/offering-IRS-1075.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-IRS-1075.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz  Please add your comment and help us in resolving this issue. Thanks.

**Comment by msbemba** [comment]
@tmoen2015 Thank you for your feedback. I have  updated the document via PR#https://github.com/MicrosoftDocs/Compliance/pull/15

Thanks
Sri

**Comment by robmazz** [comment]
Merged - closing
