### ISSUE TITLE
Nieaktualne odwołanie do wytycznych KNF oraz nieaktualne odwołanie do ustawy o ochronie danych osobowych z 1997 r.

### ISSUE THREAD

**Issue by Andrzej-Rz** [MicrosoftDocs/Compliance#16]
Artykuł odwołuje się do nieaktualnego tekstu wytycznych związanych z korzystaniem z chmury obliczeniowej przez podmioty nadzorowane ( w tym banki). Obecnie nie obowiązuje już dokument z 2017 r. tylko komunikat KNF z 23 stycznia 2020 r. dostępny pod tym adresem https://www.knf.gov.pl/knf/pl/komponenty/img/Komunikat_UKNF_Chmura_Obliczeniowa_68669.pdf

Dodatkowo nie obowiązuje już ustawa o ochronie danych osobowych z1997 r. tylko RODO

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: c6713096-318d-ad72-01a4-3a8ea34eed9e
* Version Independent ID: 5b1e9774-b519-59c0-64df-5e738a32a595
* Content: [Financial Supervision Authority (KNF) Poland - Microsoft Compliance](https://docs.microsoft.com/pl-PL/compliance/regulatory/offering-KNF-Poland)
* Content Source: [compliance/regulatory/offering-KNF-Poland.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-KNF-Poland.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@Andrzej-Rz Please write your request in English. Thanks.

**Comment by yogkumgit** [comment]
@Andrzej-Rz  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
