### ISSUE TITLE
Microsoft in-scope cloud services

### ISSUE THREAD

**Issue by ajp999** [MicrosoftDocs/Compliance#17]
[Enter feedback here]

Should the documentation be updated to highlight that Teams should be listed as in-scope service alongside Skype for Business Online?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb451de8-5273-f27c-2f5d-254fe4b6a6af
* Version Independent ID: 8910bd02-fd6d-bde9-1e0d-4a540bad2fa6
* Content: [United Kingdom Government-Cloud (G-Cloud) - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-g-cloud-uk)
* Content Source: [compliance/regulatory/offering-G-Cloud-UK.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-G-Cloud-UK.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@ajp999 - thanks for the feedback. Yes, we are looking to update this topic soon and will revamp the in-scope services listings.
