### ISSUE TITLE
The Microsoft Azure Security Response in the Cloud white paper

### ISSUE THREAD

**Issue by prootq** [MicrosoftDocs/Compliance#19]
The Microsoft Azure Security Response in the Cloud white paper link is not working anymore. I would like to see this document,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a97c02e0-84f8-3fd7-9cb3-db61a1ee5886
* Version Independent ID: 5f6ec9c6-847f-e8fe-736f-218c7044b57b
* Content: [Azure and Dynamics 365 breach notification under the GDPR - Microsoft GDPR](https://docs.microsoft.com/en-us/compliance/regulatory/gdpr-breach-azure-dynamics)
* Content Source: [compliance/regulatory/gdpr-breach-azure-dynamics.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/gdpr-breach-azure-dynamics.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@prootq - thanks for the feedback. I've updated the link to direct you to the new resource (https://docs.microsoft.com/azure/azure-government/documentation-government-overview-wwps#breach-notification-process).
