### ISSUE TITLE
When will GitHub be added to the HIPAA in-scope services?

### ISSUE THREAD

**Issue by scott-cred** [MicrosoftDocs/Compliance#21]
With the move from Azure DevOps to GitHub Enterprise, when will GitHub be added to the audited HIPAA compliant list of in-scope services?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab791a76-0f10-03bb-8de3-1a9c87282de3
* Version Independent ID: 0f9e48de-ec74-e8a1-9f25-6b4db3b1893e
* Content: [Health Insurance Portability and Accountability (HIPAA) & HITECH Acts - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-hipaa-hitech)
* Content Source: [compliance/regulatory/offering-HIPAA-HITECH.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-HIPAA-HITECH.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz  Kindly answer and help us in resolving this issue. Thanks.

**Comment by robmazz** [comment]
@scott-cred - thanks for the feedback. I'm not sure yet, but this topic is scheduled for regular review soon. I'll make sure to include your question in the review and clarify as appropriate.
