### ISSUE TITLE
Clarification on IRS 1075 only allowed in Azure Gov

### ISSUE THREAD

**Issue by bbabcock1990** [MicrosoftDocs/Compliance#22]
Hello,

Is the below statement still accurate?

**Can I use the Azure or Office 365 public cloud environments and still be compliant with IRS 1075?**

> No. The only environments where FTI can be stored and processed are Azure Government or Office 365 U.S. Government. Government customers must meet the eligibility requirements to use these environments.

With Azure Commerical supporting FedRAMP High now, does this remove the IRS 1075 Azure Government constraint?

**Comment by bbabcock1990** [comment]
Any update on this?

**Comment by yogkumgit** [comment]
@robmazz  Please add your comment and help us in resolving this issue. Thanks.

**Comment by robmazz** [comment]
@bbabcock1990 - thanks for your feedback. Please see this section (https://docs.microsoft.com/azure/compliance/offerings/offering-irs-1075#attestation-documents) in the Azure IRS 1075 offering, you'll need to coordinate with your MS service representative. Thanks!
