### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by starkwwt** [MicrosoftDocs/Compliance#24]
Can you update the "Download the CJIS implementation guidelines for Microsoft Government Cloud Services" link. This no longer goes to the appropriate resource. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33303f0a-5eda-2481-7435-a91a91e9ad63
* Version Independent ID: e2aa33ca-8cf3-31a6-89a9-3e44d3044287
* Content: [Criminal Justice Information Services (CJIS) Security Policy - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-cjis)
* Content Source: [compliance/regulatory/offering-CJIS.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-CJIS.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@starkwwt - thanks for the feedback. This resource is no longer available and I'm going to remove the sentence and link. We are in the process of updating this offering and other Azure blueprints, please use this link to track the most current blueprints - https://docs.microsoft.com/en-us/azure/governance/blueprints/overview. Thanks!
