### ISSUE TITLE
Issue with docs IRS 1075 and CJIS

### ISSUE THREAD

**Issue by tmoen2015** [MicrosoftDocs/Compliance#26]
The below comment is an opinion and not fact. 

Can I use the Azure or Office 365 public cloud environments and still be compliant with IRS 1075?
No. The only environments where FTI can be stored and processed are Azure Government or Office 365 U.S. Government. Government customers must meet the eligibility requirements to use these environments.

this is also very misleading! Many of our SLG and Federal customers us other cloud services from Salesforce, Google, AWS that are NOT CJIS or IRS 1075 audited or certified. Customers can make O365 Commercial or Microsoft Azure Commercial (MAC) as certified and ready for FTI as Office 365 Government Community Cloud (GCC) and Microsoft Azure Government (MAG). It is fact that customers are using these and storing FTI data in non-compliant services. We should modify this to something like:

Does Microsoft offer Azure or Office 365 Cloud Services that are compliant with IRS 1075 and CJIS?
Yes. Microsoft offers Government Cloud Services that are CJIS and IRS 1075 compliant. Microsoft Azure Government and Office 365 Government Community Cloud are CJIS and IRS 1075 compliant.

That is a factual and complete statement and more positive and will have better outcomes and not generate questions I have to answer all day. :-) That Microsoft’s other services cannot be made FTI compliant is an opinion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 511a3ec9-30d0-2541-b430-131354de6959
* Version Independent ID: 76e2259f-18af-ee2f-5026-bc3340a51bc3
* Content: [US Internal Revenue Service Publication 1075 - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-irs-1075?source=docs)
* Content Source: [compliance/regulatory/offering-IRS-1075.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-IRS-1075.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz  Please add your comment and help us in resolving this issue. Thanks.

**Comment by robmazz** [comment]
@tmoen2015 - thanks for the feedback. There is certainly some ambiguity here and I'll work with our legal folks to make clearer in the upcoming topic review and update. Thanks!
