### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by originalsnigelkott** [MicrosoftDocs/Compliance#28]
Azure Devops Services link to BSI is dead.

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 39286844-18be-338d-7804-3fe57fdc04b3
* Version Independent ID: ee8569c7-8be0-1a36-7824-01ed35b24942
* Content: [ISO/IEC 27001:2013 Information Security Management Standards - Microsoft Compliance](https://docs.microsoft.com/sv-SE/compliance/regulatory/offering-iso-27001)
* Content Source: [compliance/regulatory/offering-ISO-27001.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-ISO-27001.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please add your comment and help us in resolving this issue. Thanks.

**Comment by robmazz** [comment]
@originalsnigelkott - thanks for the feedback, updating topic for new link (https://www.bsigroup.com/en-US/our-services/Management-system-certification/Certificate-and-Client-Directory-Search/Certificate-Client-Directory-Search-Results/?searchkey=licence%3d%26company%3dAzure&licencenumber=IS%20619017).
