### ISSUE TITLE
Incorrect Links on Page

### ISSUE THREAD

**Issue by stephentierney-github** [MicrosoftDocs/Compliance#31]
Hi, several links on this page appear to be broken and are pointing to Microsoft Code Samples instead.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 555cb3cb-83e9-707c-3c67-5ca91e0ec61d
* Version Independent ID: e235082e-3931-7f00-87a7-f3f37129f899
* Content: [New Zealand Government Cloud Computing Security and Privacy Considerations - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-nz-cc-framework-nz)
* Content Source: [compliance/regulatory/offering-nz-cc-framework-nz.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-nz-cc-framework-nz.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@stephentierney-github - thanks for the feedback. I've updated and removed dead links , the topic updates should be live later today. Thanks!
