### ISSUE TITLE
9235166968

### ISSUE THREAD

**Issue by Artaches1973** [MicrosoftDocs/Compliance#32]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70c6b10c-7fca-7663-1ae6-1340e946a4e7
* Version Independent ID: adb6f24b-d50a-0870-8607-dcf79c8f0e56
* Content: [Russian Personal Data Localization Requirements - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-russia-data-localization)
* Content Source: [compliance/regulatory/offering-russia-data-localization.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-russia-data-localization.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@Artaches1973 Please let us know what is your feedback that can improve this document. Thanks
