### ISSUE TITLE
Links to BIR documents are not working

### ISSUE THREAD

**Issue by renevanosnabrugge** [MicrosoftDocs/Compliance#36]
The links to the document `Azure and Office 365 BIR-2012 Baseline Coverage` and `Azure and Office 365 BIR-2012 Baseline Coverage User Guide (Dutch)' are not working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 742e6a08-daf3-589b-5517-76f99a9aaed1
* Version Independent ID: 26f3d9e9-2e02-60c6-3238-24776de9e5bd
* Content: [Baseline Informatiebeveiliging Rijksdienst standard (BIR 2012) - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-bir-2012-netherlands#audits-reports-and-certificates)
* Content Source: [compliance/regulatory/offering-BIR-2012-Netherlands.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-BIR-2012-Netherlands.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@renevanosnabrugge - thanks for the feedback. The “Microsoft Cloud – Azure and Office 365 BIR 2012 Baseline Coverage” report can be downloaded from the Service Trust Portal Audit Reports - GRC Assessment Reports section here - https://servicetrust.microsoft.com/ViewPage/MSComplianceGuideV3. I'll update the links on the topic today.
