### ISSUE TITLE
New Mexico signed a CJIS Management Agreement

### ISSUE THREAD

**Issue by rickzak** [MicrosoftDocs/Compliance#37]
New Mexico recently signed a CJIS Management Agreement - can you please add it to the list of states on the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33303f0a-5eda-2481-7435-a91a91e9ad63
* Version Independent ID: e2aa33ca-8cf3-31a6-89a9-3e44d3044287
* Content: [Criminal Justice Information Services (CJIS) Security Policy - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-CJIS#cjis-status-in-the-united-states-current-as-of-9232019)
* Content Source: [compliance/regulatory/offering-CJIS.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-CJIS.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by dariomws** [comment]
Hi @rickzak, thank you for your feedback and help us to improve docs.microsoft.com.

Could you kindly provide me with an official article or document about this agreement? Thank you!

**Comment by yogkumgit** [comment]
@rickzak We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by rickzak** [comment]
Please re-open this and update the list to include the State of New Mexico.  I responded to the most recent note and received an undeliverable e-mail message.

Thanks.  Rick

Richard Zak
Director of Regulatory Compliance
US State & Local Government
Mobile: 312-953-8798
***@***.******@***.***>

[Microsoft Logo]
