### ISSUE TITLE
Wrong Hyperlink for BAA

### ISSUE THREAD

**Issue by jaredburnett** [MicrosoftDocs/Compliance#38]
Team,

This article references a now out of date HIPAA BAA. This led to a very time exhaustive M365 Business Support ticket. For reference, the most recent BAA is located here https://servicetrust.microsoft.com/ViewPage/MSComplianceGuideV3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab791a76-0f10-03bb-8de3-1a9c87282de3
* Version Independent ID: 0f9e48de-ec74-e8a1-9f25-6b4db3b1893e
* Content: [Health Insurance Portability and Accountability (HIPAA) & HITECH Acts - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-hipaa-hitech#frequently-asked-questions)
* Content Source: [compliance/regulatory/offering-HIPAA-HITECH.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-HIPAA-HITECH.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@jaredburnett - thanks for the feedback, this link has been updated and merging now.
