### ISSUE TITLE
Microsoft in-scope cloud services

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/Compliance#40]
Microsoft in-scope cloud services section mentions some of the services. WHat does it mean? Are those service PCI DSS compliant? If yes, then where can I find the audit report or certificate? I checked in Trust Center but could not find for all in-scope services for e.g. Power BI Online service, Power Apps, Power Automate etc.

So its quite confusing from the article which one are PCI DSS compliant in which region. COuld you please clarify?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3a6e0c-49bc-7290-923d-c4966f9d1de5
* Version Independent ID: b94d3d1e-d84f-f46d-c967-c80416a46f94
* Content: [Payment Card Industry (PCI) Data Security Standard (DSS) - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-pci-dss)
* Content Source: [compliance/regulatory/offering-PCI-DSS.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-PCI-DSS.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@prashant1380 - thanks for your feedback. The in-scope services listed are the services included in the audit reports. Many of the services listed are bundled in the Azure audit reports, please see this reference for more information about compliance in your region. Thanks!
