### ISSUE TITLE
Police-Assured Secure Facilities (PASF) United Kingdom - broken link

### ISSUE THREAD

**Issue by thudandblunder** [MicrosoftDocs/Compliance#43]
Hi the link to the UK official blueprint in service trust portal is broken
https://servicetrust.microsoft.com/ViewPage/UKBlueprints

The blueprint doesn't exist at that location. I believe it's been retired

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b5179f-2ed4-ed04-99c4-b02c7a72befc
* Version Independent ID: 4afa9362-930c-8521-be64-fe740aedcdc5
* Content: [Police-Assured Secure Facilities (PASF) United Kingdom - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-pasf-uk)
* Content Source: [compliance/regulatory/offering-pasf-uk.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-pasf-uk.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@thudandblunder - thanks for the feedback, the link has been updated to the most current resource. The change will be published today.
