### ISSUE TITLE
new link to dynamics guide

### ISSUE THREAD

**Issue by JesperBagh** [MicrosoftDocs/Compliance#46]
Please update the link to https://servicetrust.microsoft.com/ViewPage/MSComplianceGuide?command=Download&downloadType=Document&downloadId=fb579b09-0874-4197-a97e-a25992383482&docTab=4ce99610-c9c0-11e7-8c2c-f908a777fa4d_Compliance_Guides

on the MS trust site : https://servicetrust.microsoft.com/ViewPage/MSComplianceGuide

Since I cannot edit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a39125-16b6-7657-b5dd-210fc4d70fcf
* Version Independent ID: 298792b1-d33f-f6ba-3a3b-52358d744ace
* Content: [Good Clinical, Laboratory, and Manufacturing Practices (GxP) - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-gxp?source=docs)
* Content Source: [compliance/regulatory/offering-gxp.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-gxp.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@JesperBagh - thanks for the feedback, updated and will publish today.
