### ISSUE TITLE
Many of the links to certificates on this page are broken!

### ISSUE THREAD

**Issue by software-eras** [MicrosoftDocs/Compliance#49]
for example the link to the Azure DevOps certificate points to a BSI page that doesn't exist: 

https://www.bsigroup.com/en-US/our-services/Management-system-certification/Certificate-and-Client-Directory-Search/Certificate-Client-Directory-Search-Results/?searchkey=licence%3d619017%26company%3dAzure%2bDevOps%2bServices&licencenumber=IS%20619017

it redirects to: 

https://www.bsigroup.com/en-US/Sorry-we-could-not-find-that-page/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39286844-18be-338d-7804-3fe57fdc04b3
* Version Independent ID: ee8569c7-8be0-1a36-7824-01ed35b24942
* Content: [ISO/IEC 27001:2013 Information Security Management Standards - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-iso-27001)
* Content Source: [compliance/regulatory/offering-ISO-27001.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-ISO-27001.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by dariomws** [comment]
Hi @software-eras, thank you for your feedback.

We are aware of this issue, and we're trying to fix it. The links are right, but there is a redirection problem. If you copy and paste the links, you'll see that they work.

@robmazz FYI, same as:
https://github.com/MicrosoftDocs/Compliance/pull/23
Thank you!
