### ISSUE TITLE
Body

### ISSUE THREAD

**Issue by Body87** [MicrosoftDocs/Compliance#50]
[Ovde unesite povratne informacije]

---
#### Detalji o dokumentu

⚠ *Nemojte da uređujete ovaj odeljak. Obavezno je za povezivanje docs.microsoft.com ➟ GitHub problema.*

* ID: dd62361b-3886-f9a0-b9d5-11fcfa4f5db5
* Version Independent ID: 85288803-e652-13a0-24e9-fa1c7832863a
* Content: [Azure and Dynamics 365 accountability readiness checklist for the GDPR - Microsoft GDPR](https://docs.microsoft.com/sr-Latn-RS/compliance/regulatory/gdpr-arc-azure-dynamics)
* Content Source: [compliance/regulatory/gdpr-arc-azure-dynamics.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/gdpr-arc-azure-dynamics.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@Body87 What is your feedback with respect to this document? Please let us know.

**Comment by yogkumgit** [comment]
@Body87 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
