### ISSUE TITLE
missing content

### ISSUE THREAD

**Issue by jrohrich** [MicrosoftDocs/Compliance#55]
[Enter feedback here]
The table showing examples of data classification framework levels only has a single entry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b137099-530c-867b-cc99-55f23a7b301d
* Version Independent ID: ae5e2423-4b97-f931-1ccb-15dd2e12a898
* Content: [Data classification & sensitivity label taxonomy - Microsoft Service Assurance](https://docs.microsoft.com/en-us/compliance/assurance/assurance-data-classification-and-labels)
* Content Source: [compliance/assurance/assurance-data-classification-and-labels.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/assurance/assurance-data-classification-and-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by robmazz** [comment]
@jrohrich - thanks for the feedback, updated the topic to make it clearer that this is an example of a single classification level. Look for the changes to be published later today. Thanks!
