### ISSUE TITLE
Hello.  The NZ government-specific assurance document for D365 has disappeared from this page. Can we please have it made available again.  I have the authoritative version.  Thanks -  Russell Craig, National Technology Officer, Microsoft NZ rucraig@microsoft.com 

### ISSUE THREAD

**Issue by RussellCraig-MSFT** [MicrosoftDocs/Compliance#56]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 555cb3cb-83e9-707c-3c67-5ca91e0ec61d
* Version Independent ID: e235082e-3931-7f00-87a7-f3f37129f899
* Content: [New Zealand Government Cloud Computing Security and Privacy Considerations - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-nz-cc-framework-nz)
* Content Source: [compliance/regulatory/offering-nz-cc-framework-nz.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-nz-cc-framework-nz.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by playaspec** [comment]
They're frantically doing spin control and cleaning up after their latest breach. A _LOT_ of this stuff seems to have suddenly gone missing. Why people keep doing business with them is beyond me.

**Comment by RussellCraig-MSFT** [comment]
Hi,

Not sure what the next steps are here to get this resolved?

Regards,
Russell

**Comment by robmazz** [comment]
@RussellCraig-MSFT - since we've been coordinating on Teams internally, going to close this. We'll update the topic as soon as the document is available on the DLC. Thanks!

**Comment by RussellCraig-MSFT** [comment]
OK.  I’m trying to find someone else in the subsidiary that is a user of the DMS system to act as “signer” of the download (using DMS is a prerequisite).  SO far no luck -  none of our comms or marketing people I have spoken to have even heard of DMS ☹
