### ISSUE TITLE
The links to service trust do not work. 

### ISSUE THREAD

**Issue by Blablablablabl** [MicrosoftDocs/Compliance#57]
The links to service trust do not work. 
[Voer hier feedback in]

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: b7859b23-018c-51ac-fa2b-2932aabc00b7
* Version Independent ID: c445bea0-62e9-f875-b6f5-2688196d214b
* Content: [NEN 7510 - Microsoft Compliance](https://docs.microsoft.com/nl-nl/compliance/regulatory/offering-nen-7510-netherlands#feedback)
* Content Source: [compliance/regulatory/offering-NEN-7510-Netherlands.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-NEN-7510-Netherlands.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@please help us in resolving this issue. Thanks

**Comment by playaspec** [comment]
Yeah, good luck with that. They're actively scrubbing their initial response to the latest breach off their site. Your best bet is to search Google's cache or the WayBack Machine for copies and retain what you find. They're in cleanup mode.

**Comment by robmazz** [comment]
@Blablablablabl  - thanks for the feedback. The NEN 7510 coverage report link has been updated.
