### ISSUE TITLE
URL Link not correct

### ISSUE THREAD

**Issue by soutchilin** [MicrosoftDocs/Compliance#58]
Hello,

In the "Further details can be found in Customer Notification." the "Customer Notification" has an URL https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-breach-azure-dynamics#customer-notification that points to "404 - Page not found" page. Please provide correct link.

Kind regards,
Alexander

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cca83e2-26f2-5f48-ba7b-9e6483ca7eb0
* Version Independent ID: 68240b3c-3162-84c3-4717-13a3a9d23310
* Content: [Breach Notification - Microsoft GDPR](https://docs.microsoft.com/en-us/compliance/regulatory/gdpr-breach-notification)
* Content Source: [compliance/regulatory/gdpr-breach-notification.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/gdpr-breach-notification.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by robmazz** [comment]
@soutchilin - thanks for the feedback, I've fixed the link and updated the topic. Look for the changes in the published topic later today. Thanks!
