### ISSUE TITLE
I'd like to request this page not limit the guidance to Azure Government.  The required controls are also available in Azure Commercial, at least that is my understanding.

### ISSUE THREAD

**Issue by willstMSFT** [MicrosoftDocs/Compliance#59]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 511a3ec9-30d0-2541-b430-131354de6959
* Version Independent ID: 76e2259f-18af-ee2f-5026-bc3340a51bc3
* Content: [US Internal Revenue Service Publication 1075 - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-irs-1075)
* Content Source: [compliance/regulatory/offering-IRS-1075.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-IRS-1075.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks.

**Comment by willstMSFT** [comment]
I'm adding Rick Zak to the thread to get more perspectives on how the document could be updated.


This is the document that my customer felt contradicted our stance on IRS 1075 in commercial.



https://docs.microsoft.com/en-us/compliance/regulatory/offering-irs-1075<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fcompliance%2Fregulatory%2Foffering-irs-1075&data=04%7C01%7Cwillst%40microsoft.com%7C94f4018d05e24420f44d08d9577141d4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637636966221604954%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yGfKR%2Fa9jhsUuL575aYBYpaInShs4uW8GMJ8FZIRVd8%3D&reserved=0>



Thanks you,

WST
Azure Specialist, State and Local Government
720-528-1615 (o) | 303-618-2474 (m)
***@***.*** ***@***.***

**Comment by robmazz** [comment]
@willstMSFT - thanks for the feedback. This is one of several offerings that has two topics - one focused on O365 (the one listed here) and one focused on Azure (https://docs.microsoft.com/en-us/azure/compliance/offerings/offering-irs-1075). Happy to make the changes in the O365 version to make it more accurate. Please reach out to me on Teams or email so we can all sync. Thanks!

**Comment by robmazz** [comment]
@willstMSFT - closing this issue since we're all in the Teams thread and it's likely the Azure offering will be updated instead of this O365 offering.
