### ISSUE TITLE
Broken Link in third paragraph

### ISSUE THREAD

**Issue by bitdeft** [MicrosoftDocs/Compliance#60]
[Enter feedback here]
The first link in the doc is broken. 

Text:
Chart your Microsoft 365 compliance path and information protection strategy
Link:
https://myignite.techcommunity.microsoft.com/videos/65720

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 014c96d4-b256-7eb5-c227-3fa6090be7e7
* Version Independent ID: cb3d94bb-30a6-ccc0-9648-457e0dae770a
* Content: [Microsoft 365 ISO 27001 action plan, priorities for your first 30 days, 90 days, and beyond](https://docs.microsoft.com/en-us/compliance/regulatory/iso-action-plan)
* Content Source: [compliance/regulatory/iso-action-plan.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/iso-action-plan.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks.

**Comment by robmazz** [comment]
@BrendaCarter - if you can provide a valid link, I'll update for you if that's easier.

**Comment by robmazz** [comment]
@bitdeft - thanks for your feedback, the Ignite session has been deleted and the broken link has been removed. Thanks again!
