### ISSUE TITLE
Feedback on Microsoft 365 Risk Management program

### ISSUE THREAD

**Issue by waltgithub** [MicrosoftDocs/Compliance#61]
This document was very informative, and I appreciate Microsoft publishing it. However, what's not clear to me is how this Microsoft 365 Risk Management is applied externally and/or how it impacts customers. I'd love to see the authors expand on this. Thank you.

Respectfully,

Walter Meclazcke

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e6b203-ae4b-a316-00fa-5eb570f2f925
* Version Independent ID: b4350a2e-0877-9179-1750-d373c9c82f61
* Content: [Risk management program - Microsoft Service Assurance](https://docs.microsoft.com/en-us/compliance/assurance/assurance-risk-management-program)
* Content Source: [compliance/assurance/assurance-risk-management-program.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/assurance/assurance-risk-management-program.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz please help us in resolving this issue. Thanks

**Comment by robmazz** [comment]
@waltgithub - thanks for your feedback, I believe this issue has been addressed in a PM with Soo. Thanks!
