### ISSUE TITLE
In scope commercial products are inconsistent with GCCH products

### ISSUE THREAD

**Issue by avisuj** [MicrosoftDocs/Compliance#62]
I would expect that the in scope products for commercial services would be a super set of the in scope products for regulated clouds; instead it appears to be subset.  I suspect the in scope commercial services are out of date.  Can you please update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e19f08-8e05-7118-d051-f0eeaadd8882
* Version Independent ID: 010836ee-3833-558d-8123-89a20d7abdb9
* Content: [Web Content Accessibility Guidelines - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-WCAG-2-1)
* Content Source: [compliance/regulatory/offering-WCAG-2-1.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-WCAG-2-1.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder.

**Comment by robmazz** [comment]
@avisuj - thanks for the feedback. This topic was updated right around the time of your feedback and was reviewed by our product teams, but I'll double-check to confirm that the information is current and accurate. Thanks!
