### ISSUE TITLE
OneDrive for Business admin center no longer exists but is still being mentioned

### ISSUE THREAD

**Issue by KoenZomers** [MicrosoftDocs/Compliance#63]
OneDrive for Business admin center is mentioned on this page. This no longer exists and has been merged with the SharePoint Online Admin center instead. Update the link and possibly wording to reflect this change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d132b4c6-f3a0-b86a-0872-379740cce876
* Version Independent ID: 5ad0be6d-ba25-6c3a-5322-ec67bc13972e
* Content: [Auditing and reporting in Microsoft cloud services - Microsoft Service Assurance](https://docs.microsoft.com/en-us/compliance/assurance/assurance-auditing-and-reporting-overview)
* Content Source: [compliance/assurance/assurance-auditing-and-reporting-overview.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/assurance/assurance-auditing-and-reporting-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by robmazz** [comment]
@KoenZomers  - thanks for the feedback. Yes, this is correct and these updates are in-progress. Please check back to this page later this month. Thanks again!
