### ISSUE TITLE
No info on SOC 2 reports referenced by SOC-2 doc site

### ISSUE THREAD

**Issue by apfinger** [MicrosoftDocs/Compliance#64]
Can this info page provide links or instructions on where and how to find referenced reports?

> see separate Azure DevOps SOC 2 Type 2 attestation report

There's no guidance on where or how to acquire "Azure DevOps SOC 2 Type 2 attestation report" and other reports mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8017e3db-1948-bfbe-ebde-b95b436659ba
* Version Independent ID: 7c86a1d0-7753-8d61-6882-8b644e5fbcb0
* Content: [System and Organization Controls (SOC) 2 Type 2 - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-soc-2)
* Content Source: [compliance/regulatory/offering-soc-2.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-soc-2.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@apfinger - Thanks for the feedback. There is a section on this topic for all Azure-related SOC-2 information that points to the Azure compliance SOC-2 offering. There is a section on that topic that has a link to the DevOps report on the Service Trust Portal (https://docs.microsoft.com/azure/compliance/offerings/offering-soc-2#audit-reports), but I'll also add a direct link from this topic to make this less confusing. Thanks again!
