### ISSUE TITLE
Microsoft's DPIAs are abstracted and will be provided through this section in future updates

### ISSUE THREAD

**Issue by dombat** [MicrosoftDocs/Compliance#66]
he page says;

"Microsoft, as a processor, has a duty to assist controllers in ensuring compliance with the DPIA requirements laid out in the GDPR. To support our customers, relevant sections of Microsoft's DPIAs are abstracted and will be provided through this section in future updates with the intent of allowing controllers relying on Microsoft services to leverage the abstracts in order to create their own DPIAs."

with emphasis on this "will be provided through this section in future updates" - where can I get help with DPIA's?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87dd6312-7b6c-5535-5b12-d08ef3e46ddd
* Version Independent ID: 7e449397-c6ba-1562-d920-ac2f9ab6cc24
* Content: [General Data Protection Regulation - Microsoft GDPR](https://docs.microsoft.com/en-us/compliance/regulatory/gdpr)
* Content Source: [compliance/regulatory/gdpr.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/gdpr.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@dombat  - thanks for the feedback. I would suggest you review the DPIA topic (https://docs.microsoft.com/compliance/regulatory/gdpr-data-protection-impact-assessments) and the applicable DPIA reference for the service you are interested in, for example - for Office 365, the topic is in the same library (https://docs.microsoft.com/compliance/regulatory/gdpr-dpia-office365). You may also want to consider working with a Microsoft partner (https://appsource.microsoft.com/marketplace/partner-dir) and/or your Microsoft service account representative (https://support.serviceshub.microsoft.com/supportforbusiness).
