### ISSUE TITLE
Privacy Compliance: GDPR Schrems II - M365 Data Transfer Impact Assessment

### ISSUE THREAD

**Issue by Cro-max** [MicrosoftDocs/Compliance#67]
Hi there,
we as controller need to perform a data transfer impact assessment for the personal data being transferred to non European countries or those who are not on the list of countries with adequate protection (including US).
Can you please provide a page/or document to give guidance on how to do this with specific focus on the data flows to the US which includes the log/analytics data? 
Thx!
Christoph

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by Cro-max** [comment]
I am currently working on a transfer impact assessment for M365 for my company in our privacy management tool onetrust:
[GDPR - Transfer Impact Assessment - 1.0.pdf](https://github.com/MicrosoftDocs/Compliance/files/7495246/GDPR.-.Transfer.Impact.Assessment.-.1.0.pdf)

This needs to be done for transfers of personal data to third countries (non-EU and not on the list of countries with adequate protection). 
I know MS is working on the remediation of the issue of data residency, however currently the data transfers still exist which is the reason why we (customers) need to perform this transfer impact assessment of the parts of data being transfered.
(related blow entries on your websites: https://blogs.microsoft.com/eupolicy/2021/05/06/eu-data-boundary/ and 
 https://blogs.microsoft.com/on-the-issues/2020/11/19/defending-your-data-edpb-gdpr/) 

In the attached document you can see the level of detail we need to include in our impact assessments. Currently I am reviewing about 20 gigs of log data of my personal account provided by my tenant admin (report ran 1 month) to evaluate the data which is hopefully covering all transfers of personal data of our "standard M365 suite including ATP" e.g. in question 2.10.  Most of your clients with business in the EU will need to do such an assessment and it would be great if you could provide guidance for us to perform the assessment ourselves.
I don't expect a prefilled template, but it would be great to have a page which links the relevant content and maybe additional guidance/explanations. Also another blog entry of Brad or Julie would help as a reference that MS is aware and supportive beside the plan to ensure data residency of all personal data in the EU in 2022+.

Let me know if you need more details or we set up a short call as I know this is not an easy task for you (and me).

**Comment by robmazz** [comment]
@Cro-max - thanks for the feedback and apologies for the late response, I was on extended leave in Nov/Dec. I will forward your suggestion to the GDPR team about documenting data flows to the US for consideration. If you still need specific help with your impact assessment, you'll need to work directly with your MS representative. Thanks again for the feedback!

**Comment by Cro-max** [comment]
@robmazz: thanks for the  reply and forwarding it. 
And yes, I am looking at a tricky thing today for the DPIA of M365:
The cookies which M365 is placing e.g. in sharepoint online, excel online, outlook online. It's quite a lot and originating from various Microsoft domains. What are the purposes of these cookies e.g. to authenticate, for analytics. 
![MS Sharepoint Cookies](https://user-images.githubusercontent.com/69969551/149090514-3273b590-7c52-4ee3-b894-bcad4047654d.PNG)
How is cookie consent handled in M365, especially how is user consent gathered from users and how can a single user review (remove) consent?

**Comment by Cro-max** [comment]
Hi there, any updates especially the cookie consent from my last post is really urgent. Thx!
