### ISSUE TITLE
PCI-DSS Encryption requirements

### ISSUE THREAD

**Issue by Ryu-Syrius** [MicrosoftDocs/Compliance#68]
This document does not discuss the encryption restrictions on remote access, nor does it mention the shortfall in Windows 10 VPN Client, as does not natively support the AES128 Dillman-Huffie Group 5 encryption requirement.  

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3a6e0c-49bc-7290-923d-c4966f9d1de5
* Version Independent ID: b94d3d1e-d84f-f46d-c967-c80416a46f94
* Content: [Payment Card Industry (PCI) Data Security Standard (DSS) - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-PCI-DSS#feedback)
* Content Source: [compliance/regulatory/offering-PCI-DSS.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-PCI-DSS.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us resolving this issue. Thanks

**Comment by Ryu-Syrius** [comment]
My apologies, I do not avidly check this email.

Our organization went with AES256 encryption using DH Group 14 exchange for
our VPN.

This is natively supported on Windows 10, macOS, and iOS, yet not supported
natively in Android.

I sent Android feedback on this.  For us, it was not an issue.
