### ISSUE TITLE
Is the number of active Exchange Online databases correct?

### ISSUE THREAD

**Issue by xarmsp** [MicrosoftDocs/Compliance#69]
Currently says:
Exchange Online has 4 database availability groups, **4** active and 1 lagged by 14 days of delayed transaction logs.
Shoudl this read:
Exchange Online has 4 database availability groups, **3** active and 1 lagged by 14 days of delayed transaction logs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9c48b93-43af-4935-ef3d-f16920fef6cc
* Version Independent ID: a00db0ab-68de-f45f-c66a-480b3d35e7b6
* Content: [Malware and ransomware protection in Microsoft 365 - Microsoft Service Assurance](https://docs.microsoft.com/en-us/compliance/assurance/assurance-malware-and-ransomware-protection)
* Content Source: [compliance/assurance/assurance-malware-and-ransomware-protection.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/assurance/assurance-malware-and-ransomware-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by robmazz** [comment]
@yogkumgit - trying to verify with Exchange team.

**Comment by robmazz** [comment]
@xarmsp - thanks for the feedback, verified this with the EXO Team and will make this update.
