### ISSUE TITLE
Compliance for the Power Platform

### ISSUE THREAD

**Issue by jimmylin829** [MicrosoftDocs/Compliance#70]
The Power Platform (PowerApp and PowerAutomate) appears to be game changes from a business productivity perspective.  In order for this to be utilized for financial institutions, we would need this to be FFIEC reviewed.  Whats the timeline for Microsoft to work with the FFIEC on the Power Platform.  Thank you

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by robmazz** [comment]
@yogkumgit - this would be a question for the Power Platform team in Azure.

**Comment by yogkumgit** [comment]
@tiburd Please help us here. Thanks

**Comment by tiburd** [comment]
@yogkumgit 
Hi, Yogesh,
I sent email to someone on the Power Platform Docs team and cc'd you. 
Thanks!

**Comment by ManningTod** [comment]
The following services have achieved FFIEC certification, date achieved in parenthesis:
•	Dataverse, PPAC (11/3/2020)
•	Dataverse, PP ISV Portal Platform (1/8/2021)
•	Dataverse, PowerApps – UCI (5/1/2020)
•	Microsoft Cloud for Financial Services, Power Automate (5/31/2017)
•	Microsoft Cloud for Financial Services, Power BI (5/31/2017)
•	Microsoft Cloud for Financial Services, PPAC (11/3/2020)
•	Microsoft Cloud for Financial Services, PP ISV Portal Platform (1/8/2021)
•	Microsoft Cloud for Financial Services, PowerApps – UCI (5/1/2020)

There are a lot more certifications with even greater detail if that is needed. Bottom line – Power Platform services have achieved FFIEC certifications.

Please let me know if you have any questions about the above.

Cheers,
Tod

**Comment by yogkumgit** [comment]
@ManningTod Thank you very much for the contribution and sharing this information. @jimmylin829 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
