### ISSUE TITLE
Phase 3: Demonstrate data discovery. This option does not exist in content search

### ISSUE THREAD

**Issue by keboiyehi** [MicrosoftDocs/Compliance#73]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1593f83e-002f-42af-c868-d5a58ba57b0b
* Version Independent ID: 5e673f62-1687-f7a3-757c-2f0632ec4960
* Content: [GDPR discovery, protection, and reporting in the Microsoft 365 dev/test environment - Microsoft GDPR](https://docs.microsoft.com/en-us/compliance/regulatory/gdpr-discovery-protection-reporting-in-Office365-dev-test-environment)
* Content Source: [compliance/regulatory/GDPR-discovery-protection-reporting-in-Office365-dev-test-environment.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/GDPR-discovery-protection-reporting-in-Office365-dev-test-environment.md)
* Service: **o365-seccomp**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks.

**Comment by robmazz** [comment]
@BrendaCarter - please help in resolving this issue.

**Comment by BrendaCarter** [comment]
@robmazz - if your team is not continuing to support this article it might be a candidate for retirement.

**Comment by robmazz** [comment]
@yogkumgit - will look at whether or not to retire, no customer feedback listed. Closing
