### ISSUE TITLE
Update linked documentation

### ISSUE THREAD

**Issue by nanoonan538** [MicrosoftDocs/Compliance#74]
This appears to be linking to older documentation instead of newer assessments by Cohasset. This and might instead point to:
https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-regulatory-requirements?view=o365-worldwide#sec-17a-4f-finra-4511c-and-cftc-131c-d

https://docs.microsoft.com/en-us/microsoft-365/solutions/financial-services-secure-collaboration?view=o365-worldwide
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b088aea-d430-69be-86c8-b28c19ceff81
* Version Independent ID: e5b46e99-30de-ec3e-3bba-52825f38dc3b
* Content: [Data immutability in Microsoft 365 - Microsoft Service Assurance](https://docs.microsoft.com/en-us/compliance/assurance/assurance-data-immutability)
* Content Source: [compliance/assurance/assurance-data-immutability.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/assurance/assurance-data-immutability.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by robmazz** [comment]
@nanoonan538 - thanks for the feedback, that whitepaper link does look very dated. We'll look into replacing that with a more current and accurate link, thanks again!
