### ISSUE TITLE
Confusing instructions for "privacy contact e-mail"

### ISSUE THREAD

**Issue by daolofss** [MicrosoftDocs/Compliance#75]
[Enter feedback here]

**The article says;**

_To summarize, Office 365 asks customers to do the following to receive the benefits of our breach notification processes:
Decide on a contact to receive e-mail notifications regarding personal data breach. This contact should be aware of the controller's requirements under GDPR and should be prepared to interface with the organization's DPO and potentially the DPA shortly after receiving notification. Tenant administrators will also receive breach notifications and should similarly be aware of the controller's requirements under GDPR. Enter the privacy contact's e-mail address into the Azure Active Directory portal. If no Global Privacy Contact information is provided, Microsoft will only notify the tenant administrator._

My comment:
The comment "_Enter the privacy contact's e-mail address into the Azure Active Directory portal_" makes customers think this privacy contact will be receiving all breach notifications, but in reality this customer email is only contacted if there is a breach related to Azure Active Directory and not O365 or any other platform.

Best regards:
David Olofsson
Customer Success Account Manager
Customer Success Unit – Microsoft
Mobile: +46 734 085671
Mail: david.olofsson@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e868ae50-baa3-d037-eeae-f6927a78ed62
* Version Independent ID: b42cf3ea-04b4-9bc0-de4d-ec218fa28b53
* Content: [Breach Notification Under the GDPR - Microsoft GDPR](https://docs.microsoft.com/en-us/compliance/regulatory/gdpr-breach-office365#call-to-action-for-customers)
* Content Source: [compliance/regulatory/gdpr-breach-Office365.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/gdpr-breach-Office365.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by robmazz** [comment]
@daolofss - thanks for the feedback, the call to action section on the topic (https://docs.microsoft.com/compliance/regulatory/gdpr-breach-office365#call-to-action-for-customers) has been updated.
