### ISSUE TITLE
Export controls reference to Encryption only covers Azure, not M365. 

### ISSUE THREAD

**Issue by E-Saggese** [MicrosoftDocs/Compliance#77]
This page links to https://aka.ms/Azure-Encryption-Overview to explain the encryption options available with the Microsoft cloud, but that page only refers to Azure encryption options, and omits all Office 365 encryption options, including Microsoft Information Protection (https://docs.microsoft.com/en-us/graph/information-protection-overview) and tenant-level encryption with Customer Key (https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-service-encryption?view=o365-worldwide) which are just as important and relevant to export control regulations so they need to be referred to in this article as well. I suggest adding them to the same paragraph in which Azure encryption is referred. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d9b48a9-c8d8-6d0f-a1e9-bcbb9c998aca
* Version Independent ID: 88c7a8ab-c48b-f357-f467-4326b9d1e8c4
* Content: [US Export Administration Regulations (EAR) - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-ear)
* Content Source: [compliance/regulatory/offering-ear.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-ear.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by robmazz** [comment]
@yogkumgit - sent internal message and draft updates to @E-Saggese for review, waiting on confirmation.

**Comment by E-Saggese** [comment]
The proposed update is exactly what's needed. Please commit.

**Comment by robmazz** [comment]
@yogkumgit - I think this was applied, closing
