### ISSUE TITLE
Typo in paragraph

### ISSUE THREAD

**Issue by NathanDotTo** [MicrosoftDocs/Compliance#78]
[Enter feedback here]

See correction "... does not ..."

It is important to understand that PCI DSS compliance status for Azure, OneDrive for Business, and SharePoint Online *does* not automatically translate to PCI DSS certification for the services that customers build or host on these platforms. Customers are responsible for ensuring that they achieve compliance with PCI DSS requirements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3a6e0c-49bc-7290-923d-c4966f9d1de5
* Version Independent ID: b94d3d1e-d84f-f46d-c967-c80416a46f94
* Content: [Payment Card Industry (PCI) Data Security Standard (DSS) - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-PCI-DSS?view=o365-worldwide)
* Content Source: [compliance/regulatory/offering-PCI-DSS.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-PCI-DSS.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@NathanDotTo Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/Compliance/pull/80

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @NathanDotTo Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
