### ISSUE TITLE
Incorrect description of process and actions

### ISSUE THREAD

**Issue by MattiasAtelius** [MicrosoftDocs/Compliance#79]
In the section Call To Action we are wrongly describing how the process works. I work at Microsoft and have worked with a lot of PMs before we got it all right one this works.
The Global Privacy Contact is ONLY used for Azure AD-related incidents. It is not used for Office 365. It says that we will send emails if it's related to office 365 which is not correct.

It's referred to this in several places in this article and a few other articles as well. If you need more info please reach out to mattias.atelius@microsoft.com and I can provide the names and teams that was involved in the troubleshooting of this.

/Mattias

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e868ae50-baa3-d037-eeae-f6927a78ed62
* Version Independent ID: b42cf3ea-04b4-9bc0-de4d-ec218fa28b53
* Content: [Breach Notification Under the GDPR - Microsoft GDPR](https://docs.microsoft.com/en-us/compliance/regulatory/gdpr-breach-office365#call-to-action-for-customers)
* Content Source: [compliance/regulatory/gdpr-breach-Office365.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/gdpr-breach-Office365.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz please help us in resolving this issue. Thanks

**Comment by robmazz** [comment]
@MattiasAtelius - thanks for the feedback, the call to action section (https://docs.microsoft.com/compliance/regulatory/gdpr-breach-office365#call-to-action-for-customers) was updated.
