### ISSUE TITLE
Guidance Documentation link goes to valid download page with broken download link

### ISSUE THREAD

**Issue by gigabit-jack** [MicrosoftDocs/Compliance#82]
The link to the _guidance documentation_ under the Azure, Dynamics 365, and SOX heading takes you to a valid page, but the Download link on that page no longer works.

**Link in doc:** 
https://azure.microsoft.com/resources/microsoft-azure-guidance-for-sarbanes-oxley-sox/

**Download link on destination:** 
https://azure.microsoft.com/mediahandler/files/resourcefiles/microsoft-azure-guidance-for-sarbanes-oxley-sox/Azure%20SOX%20guidance.pdf.pdf

I also tried the download link without the extra ".pdf" at the end and it still fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6492b89-1d8b-452c-a8fc-55b661a258f9
* Version Independent ID: 3bc7f992-68dc-017d-8cd4-995934da6feb
* Content: [Sarbanes-Oxley Act of 2002 (SOX) - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-SOX)
* Content Source: [compliance/regulatory/offering-SOX.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-SOX.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@gigabit-jack Thank you for your feedback. I'm able to download it now. Could you please verify now?

Thanks
Sri
