### ISSUE TITLE
Article needs to be updated for information related to data breach notifications

### ISSUE THREAD

**Issue by shashishailaj** [MicrosoftDocs/Compliance#84]
The [Call to action for customers](https://docs.microsoft.com/en-us/compliance/regulatory/gdpr-breach-office365#call-to-action-for-customers) section needs to be updated. 

The Global Privacy Contact added in Azure AD is only for Azure AD related breach notification . It does not cover Microsoft 365 services related data breach as confirmed by Program managers internally . Also the [M365 message center FAQ talks about notifications related to M365](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/message-center?view=o365-worldwide#frequently-asked-questions) . 

Please see MicrosoftDocs/azure-docs/issues/87586 and https://github.com/MicrosoftDocs/azure-docs-pr/pull/191636 . for more information please contact me or [MattiasAtelius](https://github.com/MattiasAtelius) internally on teams. We have legal team of a huge customers questioning us on this. It would be great to get this updated. 

Thank you. 

**cc** : [MattiasAtelius](https://github.com/MattiasAtelius)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e868ae50-baa3-d037-eeae-f6927a78ed62
* Version Independent ID: b42cf3ea-04b4-9bc0-de4d-ec218fa28b53
* Content: [Breach Notification Under the GDPR - Microsoft GDPR](https://docs.microsoft.com/en-us/compliance/regulatory/gdpr-breach-office365#call-to-action-for-customers)
* Content Source: [compliance/regulatory/gdpr-breach-Office365.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/gdpr-breach-Office365.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks
