### ISSUE TITLE
dead link for Gallery Item for IT Grundschutz

### ISSUE THREAD

**Issue by floschmsft** [MicrosoftDocs/Compliance#90]
[(https://gallery.technet.microsoft.com/Azure-Germany-IT-fca4afd7) is a dead link]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71dd2699-87d8-2f73-8595-4095f466c042
* Version Independent ID: f5e03e95-b7cf-7c34-9e40-75c9bdc4e4b6
* Content: [Cloud Computing Compliance Controls Catalog (C5) - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-c5-germany)
* Content Source: [compliance/regulatory/offering-C5-Germany.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-C5-Germany.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@floschmsft - thanks for the feedback, fixed and will publish the update today.
