### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by maharumman** [MicrosoftDocs/Compliance#91]
in the FAQ section, there are two links to global azure map and global office 365 map both of them seem to be dead and lead to error or a live but blank app. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb451de8-5273-f27c-2f5d-254fe4b6a6af
* Version Independent ID: 8910bd02-fd6d-bde9-1e0d-4a540bad2fa6
* Content: [United Kingdom Government-Cloud (G-Cloud) - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-g-cloud-uk?source=docs)
* Content Source: [compliance/regulatory/offering-G-Cloud-UK.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-G-Cloud-UK.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@maharumman  - thanks for the feedback, fixed and will publish the update today.
