### ISSUE TITLE
MAS TRM referenced in article are outdated.

### ISSUE THREAD

**Issue by dvdweyer** [MicrosoftDocs/Compliance#92]
Hi,

Whilst I very much appreciate documentation on Azure that relates to MAS Technology Risk Management Guidelines (TRM), I find it a bit odd that an article from 27 January 2022 would reference the 2016 version of MAS TRM and not the current version from January 2021: https://www.mas.gov.sg/-/media/MAS/Regulations-and-Financial-Stability/Regulatory-and-Supervisory-Framework/Risk-Management/TRM-Guidelines-18-January-2021.pdf

Any chance this page will be updated soon?

Kind regards,

Donald

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f2c543-a5c6-87d4-fd3b-b96dd6cb1fa5
* Version Independent ID: e3594e11-8296-ce5d-f20c-f051ca299cc1
* Content: [Monetary Authority of Singapore (MAS) and Association of Banks in Singapore (ABS) - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-mas-abs-singapore)
* Content Source: [compliance/regulatory/offering-MAS-ABS-Singapore.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-MAS-ABS-Singapore.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@dvdweyer - thanks for the feedback, updating the link today.
