### ISSUE TITLE
aka.ms/seemail-gcio link is dead

### ISSUE THREAD

**Issue by jlaundry** [MicrosoftDocs/Compliance#93]
The link https://aka.ms/seemail-gcio (included in the Conformance Guide for Office 365 linked from this page) leads to a "We are sorry, this file no longer exists." page.

Can you please revive this link?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 555cb3cb-83e9-707c-3c67-5ca91e0ec61d
* Version Independent ID: e235082e-3931-7f00-87a7-f3f37129f899
* Content: [New Zealand Government Cloud Computing Security and Privacy Considerations - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-nz-cc-framework-nz)
* Content Source: [compliance/regulatory/offering-nz-cc-framework-nz.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-nz-cc-framework-nz.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by jlaundry** [comment]
Hi @yogkumgit @robmazz, is there any luck with this?

**Comment by robmazz** [comment]
@jlaundry - this is out of the area for the topic, but it looks like the link you referenced is archived here: https://documents.pub/document/microsoft-office-365-whitepaper-office-365-it-demonstrates-to-agencies-how-they.html?page=1

**Comment by jlaundry** [comment]
Hi @robmazz did you mean to close this ticket?

Are you going to update the aka.ms link to documentspub?
